### ISSUE TITLE
Category search is taking code in the request but the actual search is by name

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/vendure#49]
Looks like search by category has two issues;

1. While request the category code, the actual search is happening on the name.
2. It works only when we match the case of the category name

**Comment by vbabuEM** [comment]
@sreekanthmr , the reason why we use the name and not the code is that if there are two facets with the same name, automatically vendure adds a suffix to the name and makes it the code. So for example when two sellers create a facet named "category", the code of the first one is "category-1" and that of the second is "category-2". From the client side if we have to search both the sellers on category, only the name is common between the two. The code will not be. Hence we use the name. However from a beckn perspective, what we are searching is still the category code. If you think this is confusing, we can probably change the field on the beckn request and make it use descriptor.name instead of descriptor.code.

**Comment by vbabuEM** [comment]
In consultation with Sreekanth, decided to use descriptor.name instead of descriptor.code

**Comment by vbabuEM** [comment]
@sreekanthmr , I have implemented this as we discussed to use category.descriptor.name instead of category.descriptor.code. Please update the BAP side to use the right attribute.
