### ISSUE TITLE
Expose tags (facets in Vendure) associated with a product in on_search

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/vendure#57]
In on_search response, please expose facets associated with a product in Vendure under tags object.

**Comment by vbabuEM** [comment]
Use the tags field of Item to give back facets and facet_values associated with the product_variant.

**Comment by vbabuEM** [comment]
The implementation returns back one value for facets.
It also returns back category as categories are modeled as facets in Vendure. However there is a different categories field which is better for categories as it can hold multiple values.
Use the name of facet instead of code as the code values are given a numeric suffix across stores in Vendure.
